### ISSUE TITLE
Endring av passord

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMwp_admin-tweaks#10]
System admin får stadig slike e-poster: Passord fjernet og endret for bruker: beiarn

Hvor kommer disse fra, og hvorfor? Ingen skal i utgangspunktet kunne endre passord

**Comment by mariusmandal** [comment]
Admin-siden må tilpasses, og feltet "glemt passord" må modifiseres / fjernes - dette ser ut til å være feilkilden

**Comment by mariusmandal** [comment]
Sleng inn en UKM-logo samtidig da?

**Comment by mariusmandal** [comment]
https://codex.wordpress.org/Function_Reference/wp_lostpassword_url => mailto:support@ukm.no

filter logo
https://codex.wordpress.org/Plugin_API/Filter_Reference/login_head

**Comment by AsgeirSH** [comment]
Fjern "Mistet passordet ditt?" Hittekontorpassord-wtf

Bytt ut WP-logo med UKM-logo og legg inn tekst "Arrangørsystemet"

Sjekk functions.php og wp-login.php.
