### ISSUE TITLE
video_on_top: Legg inn mulighet for å lime inn UKM-tv URL

### ISSUE THREAD

**Issue by AsgeirSH** [UKMNorge/UKMwp_admin-tweaks#15]
Greit å ha denne muligheten for videoer man ikke eier selv.

( Eks. DKS-videoen)

**Comment by mariusmandal** [comment]
Nå begynner du å bli veldig brukervennlig..



Mvh,


Marius Mandal

92837360

mariusmandal@gmail.com


—Sent from Mailbox

**Comment by AsgeirSH** [comment]
Det funka ikke å legge inn Festivalfilmen on top i forrige uke, så da har vi minst ETT konkret eksempel på bruksområde... :)

**Comment by mariusmandal** [comment]
Ok da...
Løsningsforslag:
PRE-RENDER:
 - if value is not in list_of_videos: egendefinert.value=value
 - else egendefinert.value="egendefinert"
GUI: 
 - Legg til alternativet "egendefinert" i lista med value="egendefinert"
 - On Select: vis et felt under hvor man limer inn URL
LAGRING:
 - Lagre URL som egen metadata
 - Hent ut id fra url, og lagre denne som vanlig

**Comment by AsgeirSH** [comment]
Fixed in df83780. Close
