### ISSUE TITLE
Fylkeskontakter kan ikke sette ny hovedside

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMwp_admin-tweaks#3]
Finn en mulighet for å fjerne "sett standardside til"-listen fra "my sites"

**Comment by mariusmandal** [comment]
Fjern hele "my-sites.php" fra menyen
noe sånn-ish
https://github.com/UKMNorge/UKMwp_admin-tweaks/blob/master/tweak.menu.php#L17

**Comment by mariusmandal** [comment]
Fjern hele "my-sites.php" fra menyen
noe sånn-ish
https://github.com/UKMNorge/UKMwp_admin-tweaks/blob/master/tweak.menu.php#L17

**Comment by AsgeirSH** [comment]
Fixed.
