### ISSUE TITLE
Endre tekst for innlegg i admin

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMwp_admin-tweaks#7]
Utdrag og fremhevet bilde bør hete ingress og hovedbilde (?) i wp-admin for bedre forståelse blant brukerne

**Comment by mariusmandal** [comment]
er det egentlig mulig?

**Comment by AsgeirSH** [comment]
Virka ikke veldig mulig... Tror vi må hacke til mye for å få det til.

**Comment by mariusmandal** [comment]
@asgeirsh close in trello
