### ISSUE TITLE
Rediger nettsted mer tilgjengelig

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMwp_admin-tweaks#8]
Må være tilgjengelig også når man ser på nettstedet, ikke kun når man er i admin

**Comment by AsgeirSH** [comment]
Det du mener her er altså at "Kontrollpanel"-knappen som nå ligger i en hover->pulldown bør vises hele tiden når man er logget inn, eller vises en plass hele tiden uavhengig om man er innlogget?
